### ISSUE TITLE
Trailing Slashes Should Not Be Added When Route Is Empty

### ISSUE THREAD

**Issue by michaelfoster9** [scottoffen/fluenthttpclient#8]
Hello, I have a url that i need to build that looks like this:

https://www.foo.com/fs/v1/collections/Y1Q/filesystems/eJM:sync

The backend service is very particular because it can not have a trailing "/".   It doesn't look like I can build this Url with the library as it exists.

If I make the url above the base address, and then do a .UsingRoute(""), it will append a terminating backslash.  

A few things would be useful
1. If you call .UsingRoute("") with no route, and there are no query string params, then a "/" is not appended to the base url.
2. Make the HttpRequestBuilder constructor public so that I can create my own extension methods for formatting the route per my needs.

Is there anything that can be done here?  As it stands I don't see a way for me to be able to build the urls that I need.

**Comment by michaelfoster9** [comment]
UPDATE: I was able to get this to work by leaving the BaseAddress empty and then using the "UsingRoute" to be the exact url that i wanted

**Comment by scottoffen** [comment]
Still worth looking into.

**Comment by scottoffen** [comment]
I've updated the method such that if no route is provided, no trailing slash will be added.
I've also update the `.UsingRoute` extension methods so that a route value is optional.

However, if no route information is provided and the client does not have a base address specified, then an `ArgumentException` will be thrown when it attempts to send the request.

If you WANT the trailing slash, use a slash for the value of `Route`.

This will all be in the v3.0 release.
